export const samples = {
  'chat-completions': [
    {object:'chat.completion.chunk',id:'chat_demo',model:'demo',choices:[{index:0,delta:{role:'assistant',content:''},finish_reason:null}]},
    {object:'chat.completion.chunk',id:'chat_demo',choices:[{index:0,delta:{content:'Hello from '},finish_reason:null}]},
    {object:'chat.completion.chunk',id:'chat_demo',choices:[{index:0,delta:{content:'Eventport.'},finish_reason:null}]},
    {object:'chat.completion.chunk',id:'chat_demo',choices:[{index:0,delta:{tool_calls:[{index:0,id:'call_weather',type:'function',function:{name:'weather',arguments:'{"city":'}}]},finish_reason:null}]},
    {object:'chat.completion.chunk',id:'chat_demo',choices:[{index:0,delta:{tool_calls:[{index:0,function:{arguments:'"London"}'}}]},finish_reason:null}]},
    {object:'chat.completion.chunk',id:'chat_demo',choices:[{index:0,delta:{},finish_reason:'tool_calls'}]},
    {object:'chat.completion.chunk',id:'chat_demo',choices:[],usage:{prompt_tokens:12,completion_tokens:8,total_tokens:20}},
  ],
  responses: [
    {type:'response.created',response:{id:'resp_demo',status:'in_progress'}},
    {type:'response.output_item.added',output_index:0,item:{type:'message',id:'msg_demo',role:'assistant',content:[]}},
    {type:'response.content_part.added',output_index:0,item_id:'msg_demo',content_index:0,part:{type:'output_text',text:'',annotations:[]}},
    {type:'response.output_text.delta',output_index:0,item_id:'msg_demo',content_index:0,delta:'Hello from '},
    {type:'response.output_text.delta',output_index:0,item_id:'msg_demo',content_index:0,delta:'Eventport.'},
    {type:'response.output_text.done',output_index:0,item_id:'msg_demo',content_index:0,text:'Hello from Eventport.'},
    {type:'response.output_item.added',output_index:1,item:{type:'function_call',id:'fc_demo',call_id:'call_weather',name:'weather',arguments:''}},
    {type:'response.function_call_arguments.delta',output_index:1,item_id:'fc_demo',delta:'{"city":"London"}'},
    {type:'response.function_call_arguments.done',output_index:1,item_id:'fc_demo',arguments:'{"city":"London"}'},
    {type:'response.completed',response:{id:'resp_demo',status:'completed',usage:{input_tokens:12,output_tokens:8,total_tokens:20}}},
  ],
  anthropic: [
    {type:'message_start',message:{id:'msg_demo',type:'message',role:'assistant',model:'demo',content:[],stop_reason:null,stop_sequence:null,usage:{input_tokens:12,output_tokens:0}}},
    {type:'content_block_start',index:0,content_block:{type:'text',text:''}},
    {type:'content_block_delta',index:0,delta:{type:'text_delta',text:'Hello from '}},
    {type:'content_block_delta',index:0,delta:{type:'text_delta',text:'Eventport.'}},
    {type:'content_block_stop',index:0},
    {type:'content_block_start',index:1,content_block:{type:'tool_use',id:'call_weather',name:'weather',input:{}}},
    {type:'content_block_delta',index:1,delta:{type:'input_json_delta',partial_json:'{"city":"London"}'}},
    {type:'content_block_stop',index:1},
    {type:'message_delta',delta:{stop_reason:'tool_use'},usage:{output_tokens:8}},
    {type:'message_stop'},
  ],
  agui: [
    {type:'RUN_STARTED',threadId:'thread_demo',runId:'run_demo'},
    {type:'TEXT_MESSAGE_START',messageId:'msg_demo',role:'assistant'},
    {type:'TEXT_MESSAGE_CONTENT',messageId:'msg_demo',delta:'Hello from '},
    {type:'TEXT_MESSAGE_CONTENT',messageId:'msg_demo',delta:'Eventport.'},
    {type:'TEXT_MESSAGE_END',messageId:'msg_demo'},
    {type:'TOOL_CALL_START',toolCallId:'call_weather',toolCallName:'weather',parentMessageId:'msg_demo'},
    {type:'TOOL_CALL_ARGS',toolCallId:'call_weather',delta:'{"city":"London"}'},
    {type:'TOOL_CALL_END',toolCallId:'call_weather'},
    {type:'RUN_FINISHED',threadId:'thread_demo',runId:'run_demo'},
  ],
  'ai-sdk': [
    {type:'start',messageId:'msg_demo'},
    {type:'text-start',id:'text_demo'},
    {type:'text-delta',id:'text_demo',delta:'Hello from '},
    {type:'text-delta',id:'text_demo',delta:'Eventport.'},
    {type:'text-end',id:'text_demo'},
    {type:'tool-input-start',toolCallId:'call_weather',toolName:'weather'},
    {type:'tool-input-delta',toolCallId:'call_weather',inputTextDelta:'{"city":"London"}'},
    {type:'tool-input-available',toolCallId:'call_weather',toolName:'weather',input:{city:'London'}},
    {type:'finish',finishReason:'tool-calls'},
  ],
  langgraph: [
    {event:'metadata',data:{run_id:'run_demo'}},
    {event:'messages',data:[{id:'msg_demo',type:'ai',content:'Hello from '},{langgraph_step:1,langgraph_node:'agent'}]},
    {event:'messages',data:[{id:'msg_demo',type:'ai',content:'Eventport.'},{langgraph_step:1,langgraph_node:'agent'}]},
    {event:'messages',data:[{id:'msg_demo',type:'ai',content:'',tool_call_chunks:[{index:0,id:'call_weather',name:'weather',args:'{"city":"London"}'}]},{langgraph_step:1,langgraph_node:'agent'}]},
  ],
};
